### PR TITLE
Show release notes newer than installed version

### LINKED ISSUE #52: Release notes should show all changes since installed version
Currently they only show the most recent entry in `changelog`. This is fine if a user is only a version behind. But if they are more than one version behind they will not be aware of the full extent of changes.

### PR DESCRIPTION
**Pull request by joewiz**
Closes #52.

### CODE REVIEW

**Comment by joewiz** [comment]
Before:

> screen shot 2017-03-23 at 9 41 57 am

After: 

> screen shot 2017-03-23 at 9 34 43 am

**Comment by dizzzz** [comment]
how large can the list become? Is there a scroll feature?

**Comment by joewiz** [comment]
Yes, you can scroll to see content that doesn't fit in the window:

> screen shot 2017-03-23 at 9 47 30 am

Of course this PR just increases the likelihood of scrolling being required, but any single version's release notes that happened to be longer than the box could've triggered this before this PR.

**Comment by dizzzz** [comment]
thnx @joewiz !

**Pull request merged**
