### PR TITLE
ranged request for progressive fetches of users/groups

### PR DESCRIPTION
**Pull request by wshager**

### CODE REVIEW

**Comment by adamretter** [comment]
@windauer @JoernT any updates please?

**Comment by wshager** [comment]
The range is a custom header that I borrowed elsewhere. The resulting `limit(count,start,maxCount)` operator can be used to get a portion of JSON objects per request (see https://github.com/persvr/rql/). The client should look for the content-range header on the Ajax request (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range). The type of item would be JSON object. This is standardized in dojo/store, but could be used in other JSON contexts as well.

**Comment by wshager** [comment]
Sorry, I meant Ajax response.

**Comment by wshager** [comment]
Here's where I borrowed the custom "range" for JSON objects (items):
https://github.com/persvr/pintura#user-content-pagingrange-requests

The range request header is a standard one though:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

**Comment by dizzzz** [comment]
for future PRs..... please fill in the description. A PR without details makes no sense :-/

**Comment by joewiz** [comment]
@wshager Thank you for this submission, and I'm sorry it wasn't acted on. Development energies have shifted to dashboard 2.0, so while I am closing this PR please feel free to investigate whether a similar improvement is needed in 2.0 or whether it already covers your needs.

**Pull request closed without merging**
