### PR TITLE
Remove deprecated xmldb:get-current-user function

### PR DESCRIPTION
**Pull request by adamretter**
Needed for compatibility with eXist-db 5.0.0.

### CODE REVIEW

**Comment by adamretter** [comment]
@joewiz @wolfgangmm I found this one still..

**Comment by joewiz** [comment]
Oddly, `getCurrentUser.xql` isn't called anywhere in the source code. Thus I think we could safely delete it. 

@craigberry Strangely, I ran the latest version of `audit_removals.pl` from (https://github.com/eXist-db/exist/issues/2626) on the dashboard repository, and it didn't flag this function that Adam caught in this PR. Do you have any idea why? This instance is caught, but the fact that the script missed this one makes me wonder if there are others it might've missed too?

**Comment by adamretter** [comment]
@joewiz hmmm... I think it must be linked somewhere, as I found the error when RESTXQ scanned the files for compilation

**Comment by craigberry** [comment]
> Oddly, `getCurrentUser.xql` isn't called anywhere in the source code. Thus I think we could safely delete it.
> 
> @craigberry Strangely, I ran the latest version of `audit_removals.pl` from ([eXist-db/exist#2626](https://github.com/eXist-db/exist/issues/2626)) on the dashboard repository, and it didn't flag this function that Adam caught in this PR. Do you have any idea why? This instance is caught, but the fact that the script missed this one makes me wonder if there are others it might've missed too?

I see what happened.  In order avoid false positives for things like:

`declare variable $m as map()`

where `map` is not a function call, my regex forbids a closing paren immediately after the opening paren.  Which means that `deprecated:func($foo)` will get picked up, but `deprecated:func()` will not.  So yes, there are probably a bunch of function calls that take no arguments that are getting missed.   Possibly I can fix that by allowing the closing paren but forbidding that the candidate function name is preceded by the word " as " but I don't know XQuery well enough to be confident I can identify with complete precision all the cases where `map` is a function while avoiding all the cases where it's not.  I'll see what I can come up with and post a revision in ([eXist-db/exist#2626](https://github.com/eXist-db/exist/issues/2626)).

**Pull request merged**
